config/routes.rb
Rails.application.routes.draw do
  root 'bookings#index'
  resources :bookings
  resources :users
  resources :bikes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
    validates :name, presence: true, uniqueness: true  
    has_many :bikes, :through => :bookings 
    has_many :bookings, :dependent => :destroy
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :bike
  belongs_to :user
  validate :date_validation

  def date_validation
    if self.start >= self.end
        errors.add(:start, "Start date cant be equal or negative ") 
    end
    @bookings = Booking.all
    @bookings.each do |item|
      if self != item && self.start < item.end && self.end > item.start
      errors.add(:base, "already reserved") 
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :users, :through => :bookings 
    has_many :bookings, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update, :destroy]

  # GET /bikes
  # GET /bikes.json
  def index
    @bikes = Bike.all
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show
  end

  # GET /bikes/new
  def new
    @bike = Bike.new
  end

  # GET /bikes/1/edit
  def edit
  end

  # POST /bikes
  # POST /bikes.json
  def create
    @bike = Bike.new(bike_params)

    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render :show, status: :created, location: @bike }
      else
        format.html { render :new }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bikes/1
  # PATCH/PUT /bikes/1.json
  def update
    respond_to do |format|
      if @bike.update(bike_params)
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { render :show, status: :ok, location: @bike }
      else
        format.html { render :edit }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike.destroy
    respond_to do |format|
      format.html { redirect_to bikes_url, notice: 'Bike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bike
      @bike = Bike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bike_params
      params.require(:bike).permit(:name)
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:bike_id, :user_id, :start, :end)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bikes/_form.html.erb
<%= form_with(model: bike, local: true) do |form| %>
  <% if bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
      <% bike.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bikes/edit.html.erb
<h1>Editing Bike</h1>

<%= render 'form', bike: @bike %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>

app/views/bikes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bikes</h1>

<table class="table table-hover table-aut" >
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bikes.each do |bike| %>
      <tr>
        <td><%= bike.name %></td>
        <td><%= link_to '', bike, :class=>"far fa-eye" %></td>
        <td><%= link_to '', edit_bike_path(bike), :class=>"fas fa-edit" %></td>
        <td><%= link_to '',  bike, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"far fa-trash-alt" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '', new_bike_path, :class=>"fas fa-plus-circle addico" %>


        

app/views/bikes/new.html.erb
<h1>New Bike</h1>
<div class="formstyle">
<%= render 'form', bike: @bike %>

<%= link_to '', bikes_path, :class=>"fas fa-backward addico" %>
</div>

app/views/bikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bike.name %>
</p>

<%= link_to 'Edit', edit_bike_path(@bike) %> |
<%= link_to 'Back', bikes_path %>

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bike_id %>
    <%= form.collection_select(:bike_id, Bike.all, :id, :name, { :prompt => 'Select a Ride', :selected => @booking.user_id }, { class: 'form-control' }) %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select(:user_id, User.all, :id, :name, { :prompt => 'Select User', :selected => @booking.user_id }, { class: 'form-control' }) %>
  </div>

  <div class="field date-form">
    <%= form.label :start %>
    <%= form.datetime_select :start %>
  </div>

  <div class="field date-form">
    <%= form.label :end %>
    <%= form.datetime_select :end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table class="table table-hover table-aut">
  <thead>
    <tr>
      <th>Bike</th>
      <th>User</th>
      <th>Start</th>
      <th>End</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.sort_by(&:start).each do |booking| %>
      <tr>
        <td><%= booking.bike.name %></td>
        <td><%= booking.user.name %></td>
        <td><%= booking.start %></td>
        <td><%= booking.end %></td>
        <td><%= link_to '', booking, :class=>"far fa-eye" %></td>
        <td><%= link_to '', edit_booking_path(booking), :class=>"fas fa-edit" %></td>
        <td><%= link_to '', booking, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"far fa-trash-alt" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '', new_booking_path, :class=>"fas fa-plus-circle addico" %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>
<div class="new-booking">
<%= render 'form', booking: @booking %>

<%= link_to '', bookings_path, :class=>"fas fa-backward addico" %>
</div>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bike:</strong>
  <%= @booking.bike %>
</p>

<p>
  <strong>User:</strong>
  <%= @booking.user %>
</p>

<p>
  <strong>Start:</strong>
  <%= @booking.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @booking.end %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bike Rental App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
  <div class="header">
<nav class="navbar navbar-expand-lg navbar-light ">
  <a class="navbar-brand" >
  <%= link_to root_path do %>
   <%= image_tag("logos/autentica-logo.png") %>
<% end %>
   
  </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse nav-links" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
     
          <%= link_to "Home", root_path, :class => "nav-link active" %>
            
      </li>
      <li class="nav-item">
       
          <%= link_to "Users", users_path, :class => "nav-link" %>
       
      </li>
            <li class="nav-item">
          
          <%= link_to "Bikes", bikes_path, :class => "nav-link" %>
         
      </li>
    </ul>
  </div>
</nav>
</div>
<div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-hover table-aut">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to '', user, :class=>"far fa-eye" %></td>
        <td><%= link_to '', edit_user_path(user), :class=>"fas fa-edit" %></td>
        <td><%= link_to '',  user, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"far fa-trash-alt" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '', new_user_path, :class=>"fas fa-plus-circle addico" %>

        

app/views/users/new.html.erb
<h1>New User</h1>
<div class="formstyle">
<%= render 'form', user: @user %>

<%= link_to '', users_path, :class=>"fas fa-backward addico" %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>